apiVersion: kuttl.dev/v1beta1
kind: TestSuite
kindContainers:
  - vectorized/redpanda-operator:latest
  - vectorized/configurator:latest
testDirs:
  - ./tests/produce-consume
kindNodeCache: false
skipDelete: true
commands:
  - command: "kubectl taint nodes -l node-role.kubernetes.io/master= node-role.kubernetes.io/master:NoSchedule-"
  - command: "./hack/install-cert-manager.sh"
  - command: "kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml"
  - command: "make deploy"
  - command: "./hack/wait-for-webhook-ready.sh"
artifactsDir: tests/_produce_consume_e2e_artifacts
timeout: 300
reportFormat: xml
parallel: 1
